
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run add_numbers script
          command: |
            . venv/bin/activate
            python Add_numbers.py

workflows:
  version: 2
  build_and_run:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
